// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POC_DotMim.Sync.Models;

#nullable disable

namespace POC_DotMim.Sync.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    partial class LocalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POC_DotMim.Sync.Models.Audio", b =>
                {
                    b.Property<Guid>("AudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TennantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AudioId");

                    b.HasIndex("TennantId");

                    b.ToTable("Audios");
                });

            modelBuilder.Entity("POC_DotMim.Sync.Models.Led", b =>
                {
                    b.Property<Guid>("LedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("LedEffectId")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("TennantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LedId");

                    b.HasIndex("LedEffectId");

                    b.HasIndex("TennantId");

                    b.ToTable("Led");
                });

            modelBuilder.Entity("POC_DotMim.Sync.Models.LedEffect", b =>
                {
                    b.Property<short>("LedEffectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("LedEffectId"));

                    b.HasKey("LedEffectId");

                    b.ToTable("LedEffect");
                });

            modelBuilder.Entity("POC_DotMim.Sync.Models.Tennant", b =>
                {
                    b.Property<Guid>("TennantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TennantId");

                    b.ToTable("Tennants");
                });

            modelBuilder.Entity("POC_DotMim.Sync.Models.Audio", b =>
                {
                    b.HasOne("POC_DotMim.Sync.Models.Tennant", "Tennant")
                        .WithMany("Audios")
                        .HasForeignKey("TennantId");

                    b.Navigation("Tennant");
                });

            modelBuilder.Entity("POC_DotMim.Sync.Models.Led", b =>
                {
                    b.HasOne("POC_DotMim.Sync.Models.LedEffect", "LedEffect")
                        .WithMany("Leds")
                        .HasForeignKey("LedEffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POC_DotMim.Sync.Models.Tennant", "Tennant")
                        .WithMany("Leds")
                        .HasForeignKey("TennantId");

                    b.Navigation("LedEffect");

                    b.Navigation("Tennant");
                });

            modelBuilder.Entity("POC_DotMim.Sync.Models.LedEffect", b =>
                {
                    b.Navigation("Leds");
                });

            modelBuilder.Entity("POC_DotMim.Sync.Models.Tennant", b =>
                {
                    b.Navigation("Audios");

                    b.Navigation("Leds");
                });
#pragma warning restore 612, 618
        }
    }
}
